### ISSUE TITLE
Inline Expressions Eat Subsequent Space Character

### ISSUE THREAD

**Issue by mnbroatch** [alforno/bondage.js#2]
```
{
  body: "1 + 1 is {1 + 1} and that's cool\n"
  tags: ""
  title: "Start"
}
```

yields "1 + 1 is 2and that's cool"

**Comment by alforno** [comment]
I have spent several hours trying to fix this in the past and was not successful. I can't remember the details now, but I think was an issue with the lexer. If I'm remember correctly, double space after the expression is a work-around.

**Comment by mnbroatch** [comment]
Oh hey thanks for checking these out! I have forked your branch and I'm currently working on these issues myself, including migration to 2.0. I'm happy to do some pull requests or I can just maintain my own fork for now if you're not feeling it at the moment. Yay 2.0!

**Comment by alforno** [comment]
I used your code change to the lexer which fixes this. It works like a charm. 

> I'm happy to do some pull requests or I can just maintain my own fork for now if you're not feeling it at the moment. Yay 2.0!

I'd feel bad if I held you up and I am not yet committed to moving this to 2.0. I'll have to make some time to assess the effort it will take to change my projects that are dependent on my own fork of bondagejs. In the meantime, if I see something that you have implemented, like this fix, I will manually merge the code and give you full credit in the comments.
